// countryData.js
export const countries = [
    { name: "United States", code: "US" },
    { name: "China", code: "CN" },
    { name: "India", code: "IN" },
    { name: "Indonesia", code: "ID" },
    { name: "Pakistan", code: "PK" },
    { name: "Brazil", code: "BR" },
    { name: "Nigeria", code: "NG" },
    { name: "Bangladesh", code: "BD" },
    { name: "Russia", code: "RU" },
    { name: "Mexico", code: "MX" },
    { name: "Japan", code: "JP" },
    { name: "Ethiopia", code: "ET" },
    { name: "Philippines", code: "PH" },
    { name: "Egypt", code: "EG" },
    { name: "Vietnam", code: "VN" },
    { name: "Germany", code: "DE" },
    { name: "Turkey", code: "TR" },
    { name: "Iran", code: "IR" },
    { name: "Thailand", code: "TH" },
    { name: "France", code: "FR" },
    { name: "United Kingdom", code: "GB" },
    { name: "Italy", code: "IT" },
    { name: "South Africa", code: "ZA" },
    { name: "Tanzania", code: "TZ" },
    { name: "Myanmar", code: "MM" },
    { name: "South Korea", code: "KR" },
    { name: "Colombia", code: "CO" },
    { name: "Kenya", code: "KE" },
    { name: "Spain", code: "ES" },
    { name: "Argentina", code: "AR" },
    { name: "Uganda", code: "UG" },
    { name: "Ukraine", code: "UA" },
    { name: "Sudan", code: "SD" },
    { name: "Iraq", code: "IQ" },
    { name: "Poland", code: "PL" },
    { name: "Canada", code: "CA" },
    { name: "Morocco", code: "MA" },
    { name: "Saudi Arabia", code: "SA" },
    { name: "Uzbekistan", code: "UZ" },
    { name: "Peru", code: "PE" },
    { name: "Angola", code: "AO" },
    { name: "Malaysia", code: "MY" },
    { name: "Afghanistan", code: "AF" },
    { name: "Venezuela", code: "VE" },
    { name: "Nepal", code: "NP" },
    { name: "Yemen", code: "YE" },
    { name: "Ghana", code: "GH" },
    { name: "Mozambique", code: "MZ" },
    { name: "North Korea", code: "KP" },
    { name: "Taiwan", code: "TW" },
    // Add more as needed
  ];
  